language: java

os:
  - linux

jdk:
  - openjdk14

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - ./mvnw clean install -Dmaven.test.failure.ignore=true

#after_script:
#  - cat /home/travis/.npm/_logs/*.log

# CI 실행 완료시 메일로 알람
#notifications:
#  email:
#    recipients:
#      - advenoh@gmail.com